#!/usr/bin/env ruby
$VERBOSE=nil # Shut up JRuby warnings on Travis
require 'gherkin/parser'
require 'gherkin/token_formatter_builder'

parser = Gherkin::Parser.new(Gherkin::TokenFormatterBuilder.new)
files = ARGV
files.each do |file|
  File.open(file, 'r:UTF-8') do |io|
    File.write("#{file}.tokens", parser.parse(io))
  end
end
